project:
  type: book
  output-dir: docs

book:
  title: "Geocomputation with Julia"
  page-footer: "Geocomputation with Julia was written by ."
  # number-sections: true
  author: ""
  description: | 
    An introductory resource for working with geographic data in Julia
  #cover-image: https://geocompx.org/static/img/book_cover_py_tmp_small.png
  site-url: https://jl.geocompx.org
  repo-url: https://github.com/geocompx/geocompjl/
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  #google-analytics: G-ZEMGTY4VV3
  #favicon: favicon-32x32.png
  chapters:
    - index.qmd
    - references.qmd

format:
  html: 
    theme: flatly
    code-link: true
    template-partials: [helpers/toc.html, helpers/title-block.html]
    toc-title: "On this page"
    code-overflow: wrap
    toc-depth: 4
  # pdf:
  #   documentclass: krantz
  #   monofont: 'Source Code Pro'
  #   monofontoptions: 
  #     - Scale=0.7
  #   pdf-engine: xelatex
  #   keep-tex: true
  #   number-sections: true
  #   top-level-division: chapter
  #   include-before-body: helpers/before_body.tex
  #   include-in-header: 
  #     text: |
  #       \AtBeginEnvironment{longtable}{\footnotesize}
  #       \usepackage{makeidx}
  #       \usepackage{gensymb}
  #       \usepackage{cjhebrew}
  #       \makeindex
  #   include-after-body: 
  #     text: |
  #       \printindex

jupyter: julia-1.11
bibliography: geocompr.bib
