---
engine: julia
project:
  execute-dir: project
---

# Attribute data operations {#sec-attr}

```{julia}
#| echo: false
#| output: false
# Workaround for QuartoNotebookRunner bug
# https://github.com/PumasAI/QuartoNotebookRunner.jl/pull/184
endswith(pwd(), "geocompjl") || cd("..")
mkpath("output")
```

## Prerequisites {.unnumbered}

This chapter requires the following packages to be installed and attached:

```{julia}
#| output: false
# Tabular data access and manipulation
using DataFrames
# Vector data access and manipulation
using GeoDataFrames
import GeoInterface as GI
# Raster data access and manipulation (requires ArchGDAL for file I/O)
using Rasters
import ArchGDAL
# "Categorical" / "factor" vectors in Julia
using CategoricalArrays
# CSV file reading
using CSV
# Statistics
using Statistics, StatsBase

# Disambiguate functions exported by multiple packages
const combine = DataFrames.combine
const groupby = DataFrames.groupby
```

## Introduction

<!-- ### Vector data attributes -->

Attribute data is non-spatial information associated with geographic (geometry) data.
A bus stop provides a simple example: its position would typically be represented by latitude and longitude coordinates (geometry data), in addition to its name.
The [Elephant & Castle / New Kent Road](https://www.openstreetmap.org/relation/6610626) stop in London, for example has coordinates of -0.098 degrees longitude and 51.495 degrees latitude, which can be represented as `GI.Point(-0.098, 51.495)` in the `GeoInterface` representation described in Chapter \@ref(spatial-class).
Attributes, such as *name*, of the `POINT` feature (to use simple features terminology) are the topic of this chapter.

TODO: add figure with bus stop
```{julia}
#| echo: false
#| eval: false
# Aim: find a bus stop in central London
using LightOSM, Extents
london_coords = (-0.1, 51.5)
london_bb = Extents.Extent(X = (-0.11, -0.09), Y = (51.49, 51.51))
osm_data = opq(bbox = london_bb) |> 
  add_osm_feature(key = "highway", value = "bus_stop") |> 
  osmdata_sf()
osm_data_points = osm_data$osm_points
osm_data_points[4, ]
point_vector = round(sf::st_coordinates(osm_data_points[4, ]), 3)
point_df = data.frame(name = "London bus stop", point_vector)
point_sf = sf::st_as_sf(point_df, coords = c("X", "Y"))
```

<!-- ### Raster data attributes -->

Another example is the elevation value (attribute) for a specific grid cell in raster data.
Unlike the vector data model, the raster data model stores the coordinate of the grid cell indirectly, meaning the distinction between attribute and spatial information is less clear.
To illustrate the point, think of a pixel in the 3^rd^ row and the 4^th^ column of a raster matrix.
Its spatial location is defined by its index in the matrix: move from the origin four cells in the x direction (typically east and right on maps) and three cells in the y direction (typically south and down).
The raster's *lookup* defines the distance for each x- and y-step.
The lookups are a vital component of raster datasets, which specifies how pixels relate to spatial coordinates (see also Chapter \@ref(spatial-operations)).

This chapter teaches how to manipulate geographic objects based on attributes such as the names of bus stops in a vector dataset and elevations of pixels in a raster dataset.
For vector data, this means techniques such as subsetting and aggregation (see Sections \@ref(vector-attribute-subsetting) to \@ref(vector-attribute-aggregation)).
Sections \@ref(vector-attribute-joining) and \@ref(vec-attr-creation) demonstrate how to join data onto simple feature objects using a shared ID and how to create new variables, respectively.
Each of these operations has a spatial equivalent:
the `select` function in **DataFrames.jl**, for example, works equally for subsetting objects based on their attribute and spatial objects; you can also join attributes in two geographic datasets using spatial joins.
This is good news: skills developed in this chapter are cross-transferable.

After a deep dive into various types of *vector* attribute operations in the next section, *raster* attribute data operations are covered.
Creation of raster layers containing continuous and categorical attributes and extraction of cell values from one or more layer (raster subsetting) (Section \@ref(raster-subsetting)) are demonstrated.
Section \@ref(summarizing-raster-objects) provides an overview of 'global' raster operations which can be used to summarize entire raster datasets.
Chapter \@ref(spatial-operations) extends the methods presented here to the spatial world.


## Vector attribute manipulation


Geographic vector datasets are well supported in Julia, and are usually represented as `DataFrame`s.  Unlike R and Python, Julia's **GeoInterface.jl** ecosystem does not have a single `sf` class, and so the package **GeoDataFrames.jl** extends Julia's **DataFrames.jl** package to add spatial metadata and file I/O capabilities.  
Geospatial data frames have a `geometry` column which can contain a range of geographic entities (single and 'multi' point, line, and polygon features) per row.

Data frames (and geospatial tables like geographic databases, shapefiles, GeoParquet, GeoJSON, etc.) have one column per attribute variable (such as "name") and one row per observation or *feature* (e.g., per bus station).

Many operations are available for attribute data, as shown in the wonderful [DataFrames.jl documentation](https://dataframes.juliadata.org/stable/).

::: {.callout-note}
## Geometry in geographic tables

The column of a geographic table that holds geometry is typically called `geometry` or `geom`, but any name can be used.

You can discover the names of the geometry columns in a geospatial table using `GI.geometrycolumns(table)` - typically, `first(GI.geometrycolumns(table))` is assumed to be the geometry column.

There is a developing convention to indicate the geometry columns in metadata using the `GEOINTERFACE:geometrycolumns` key.  
GeoDataFrames.jl adopts and implements this convention for the `DataFrame` type.
:::

There are many table manipulation packages in Julia, all of which are compatible with `DataFrame` objects.  
We provide an abbreviated list here, and you can find more information in the [DataFrames.jl documentation on data manipulation frameworks](https://dataframes.juliadata.org/stable/man/querying_frameworks/#Data-manipulation-frameworks).  
They all implement functionality similar to **dplyr** or **LINQ**. 

- **DataFramesMeta.jl** provides a convenient yet fast macro-based interface to work with `DataFrame`s, via its `@chain`, `@transform`, `@select`, `@combine`, and various other macros.  The `@chain` macro is similar to the `|>` and `%>%` operators in R.  **DataFramesMacros.jl** is an alternative implementation with better support for multi-column transformations.
- **TidierData.jl** is heavily inspired by the dplyr and tidyr R packages (part of the R tidyverse), which it aims to implement using pure Julia by wrapping DataFrames.jl.  Its entry point is also the `@chain` macro, and it uses tidy expressions as in the R tidyverse.
- **Query.jl** is a package for querying Julia data sources. It can filter, project, join and group data from any iterable data source, and is heavily inspired by [**LINQ**](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/indexq).

We also recommend the following resources for further reading:
- https://juliadatascience.io/
- https://github.com/bkamins/JuliaForDataAnalysis

### Basic `DataFrame` operations

Before using these capabilities, it is worth re-capping how to discover the basic properties of vector data objects.
Let's start by inspecting the `world.gpkg` dataset from `data/`:

```{julia}
world = GeoDataFrames.read("data/world.gpkg")
```

We can get a visual overview of the dataset by showing it (simply type the variable name in the REPL).  From this we can see an abbreviated view of its contents.

<!-- #### Inspection and description -->

But what is it?  We can check the type:

```{julia}
typeof(world) # `DataFrame`
```

and the size:

```{julia}
size(world) # it's a 2 dimensional object, with 177 rows and 11 columns
```

We can also use the `describe` function to get a summary of the dataset:

```{julia}
describe(world)
```

This is pretty useful - we can see the type and some descriptive values for each column.  `describe` is incredibly versatile, and you can see the docstring in the Julia REPL by typing `?describe`.

Notice that the first column, `:geom`, is composed of `IGeometry{wkbMultiPolygon}` objects.  This is the geometry column, and it's loaded by `ArchGDAL.jl`, which allows I/O from a truly massive range of geospatial data formats.

We can also get some geospatial information - `GI.geometrycolumns(world)` returns `{julia} GI.geometrycolumns(world)`, and `GI.crs(world)` returns `{julia} GI.crs(world)`.

::: {.callout-note collapse="false"}

## Dropping geometries

We can drop the geometry column by subsetting the `DataFrame`, as you'll see in @sec-vec-attr-subsetting.

```{julia}
world_without_geom = world[:, Not(GI.geometrycolumns(world)...)]
```


Dropping the geometry column before working with attribute data can be sometimes be useful; data manipulation processes can run faster when they work only on the attribute data and geometry columns are not always needed.
For most cases, however, it makes sense to **keep** the geometry column.
Becoming skilled at geographic attribute data manipulation means becoming skilled at manipulating data frames.

:::

### Vector attribute subsetting {#sec-vec-attr-subsetting}

There are multiple ways to subset data in Julia.  
First, and probably most simply, we can index into the DataFrame object using a few kinds of selectors.  This can select rows and columns.  

Indices are placed inside square brackets placed directly after a data frame object name, and specify the elements to keep.

Rows are referred to using integers, and columns may be referred to using integers or symbols (`:name`).

::: {.callout-note collapse="true"}

## Recap: indexing in Julia

Indexing in Julia is 1-based, like R, and unlike Python which is 0-based.

It's performed using the `[inds...]` operator.  The `:` operator is used to select all elements in that dimension, and you can select a range using `start:stop`. 
You can also pass vectors of indices or `bo`olean values to select specific elements.

In DataFrames.jl, you can construct a view over all rows by using the `!` operator, like `world[!, :pop]` (in place of `world[:, :pop]`).  This syntax is also needed when modifying the entire column, or creating a new column.
:::

Rows are always the first argument, and then columns go in the second position.  We can select the first 5 rows of the `:pop_est` column, like so:


```{julia}
world[1:5, :pop]
```

This returns a vector, since we've only selected a single column.  We can also select multiple columns by passing a vector of column names:

```{julia}
world[5:end, [:pop, :continent]]
```

and note that this returns a new DataFrame with only the selected columns.

We can also select using negations via the `Not` function:

```{julia}
world[1:5 ,Not(:pop)]
```

or

```{julia}
world[Not(1:150) , :]
```

You can pass any collection of indices to `Not`, and it will cause all elements in the dataframe that are not in that collection to be selected.


Here's a small exercise: guess the number of rows and columns in the `DataFrame` objects returned by each of the following commands, then check your answer by executing the commands in Julia.

```{julia}
#| eval: false
world[1:6, ]    # subset rows by position
world[:, 1:3]    # subset columns by position
world[1:6, 1:3] # subset rows and columns by position
world[:, [:name_long, :pop]] # columns by name
world[:, [true, true, false, false, false, false, false, true, true, false, false]] # by logical indices
world[:, 888] # an index representing a non-existent column
```


We can also drop all missing values in a column using the `dropmissing` function:

```{julia}
world_with_area = dropmissing(world, :area_km2)
```

There is also a mutating version of `dropmissing`, called `dropmissing!`, which modifies the input in place.

<!-- #### Selecting via predicate -->

We can also subset by a boolean vector, computed on some predicate.  
Earlier on, we saw that we could extract a column as a vector using `df.columnname`.  

We can use this vector of values to create a _boolean vector_ (sometimes called a _logical_ vector in R) that we can use to index into the DataFrame.

Let's select all countries whose surface area is smaller than 10,000 km^2.
```{julia}
countries_to_select = world_with_area.area_km2 .< 10_000
```

This is a simple vector, with boolean elements and the same length as the number of rows in the DataFrame.  
We use it to select all rows in the DataFrame where its value is `true`.

```{julia}
world_with_area[countries_to_select, :]
```

A more concise way to achieve the same result, without the intermediate array, is `world_with_area[world_with_area.area_km2 .< 10_000, :]`.  
This syntax is applicable to columns too!

There are ways to achieve this result using all of the DataFrame manipulation packages mentioned above.


::: {.panel-tabset}

## DataFrames.jl

DataFrames.jl also defines a `subset` function, which is another way to achieve this result:

```{julia}
subset(world_with_area, :area_km2 => ByRow(x -> x < 10_000))
```

## DataFramesMeta.jl

DataFramesMeta.jl provides a convenient syntax for subsetting DataFrames using a DSL that closely resembles the tidyverse.

```{julia}
#| eval: false
using DataFramesMeta

@chain world_with_area begin
    @subset @byrow (:area_km2 < 10_000)
    select(:name_long, :area_km2)
end
``` 

## TidierData.jl

TidierData.jl provides a convenient syntax for subsetting DataFrames using a DSL that closely resembles the tidyverse.  

```{julia}
#| eval: false
using TidierData

@chain world_with_area begin
    @subset @byrow (:area_km2 < 10_000)
    select(:name_long, :area_km2)
end
```

## Query.jl

Query.jl provides a convenient syntax for subsetting DataFrames using a DSL that closely resembles the tidyverse.  

```{julia}
#| eval: false
using Query

@from row in world_with_area |>
@where row.area_km2 < 10_000 |>
@select {name_long = row.name_long, area_km2 = row.area_km2} |>
DataFrame

```

:::

#### Subsetting by predicate

We saw how we could use a boolean vector to index into a DataFrame to select rows where the boolean is `true`.  
However, this means we have to create the boolean vector, and while powerful, it can be clunky.

Instead, DataFrames.jl offers several ways we can do this.  First is the `subset` function, which we just saw in the tabset above:

```{julia}
small_countries = subset(world_with_area, :area_km2 => ByRow(<(10_000)))
```

### Chaining operations

DataFrames.jl functions are mature, stable and widely used, making them a rock solid choice, especially in contexts where reproducibility and reliability are key.

Functions from the DataFrames manipulation packages mentioned earlier (DataFramesMeta.jl, TidierData.jl, and Query.jl) are also available, and quite stable at this point.
They offer "tidy" workflows which can sometimes be more intuitive and productive for interactive data analysis, as well as easier to reason about.

The following example demonstrates chaining multiple operations using DataFramesMeta.jl's `@chain` macro.
We filter Asian countries, select specific columns, and take the first 5 rows:

```{julia}
using DataFramesMeta
asia_sample = @chain world begin
    @subset(:continent .== "Asia")
    @select(:name_long, :continent, :pop)
    first(5)
end
```

This is equivalent to the following nested DataFrames.jl operations:

```{julia}
asia_sample2 = first(
    select(
        subset(world, :continent => ByRow(==("Asia"))),
        [:name_long, :continent, :pop]
    ),
    5
)
```

Each approach has advantages: chained operations read top-to-bottom like a pipeline, while nested operations are explicit about function composition.
For interactive analysis, chaining is often more intuitive.

### Vector attribute aggregation {#sec-vector-attribute-aggregation}

Aggregation involves summarizing data based on one or more *grouping variables*, typically values in a column of the data frame to be aggregated.
Geographic aggregation is covered in the next chapter; here we focus on attribute-based aggregation.

A classic example is calculating the number of people per continent based on country-level data.
The `world` dataset contains the necessary ingredients: the columns `pop` and `continent`, the population and the grouping variable, respectively.
The aim is to find the `sum()` of country populations for each continent.

In DataFrames.jl, attribute-based aggregation is achieved using `groupby` and `combine`:

```{julia}
world_agg1 = combine(
    groupby(dropmissing(world, :pop), :continent),
    :pop => sum => :total_pop
)
```

The result is a (non-spatial) table with six rows, one per continent, and two columns reporting the name and total population of each continent.

We can perform more complex aggregations by passing multiple aggregation expressions.
The following calculates population sum, area sum, and country count per continent:

```{julia}
world_agg2 = combine(
    groupby(dropmissing(world, [:pop, :area_km2]), :continent),
    :pop => sum => :total_pop,
    :area_km2 => sum => :total_area,
    :name_long => length => :n_countries
)
```

Using DataFramesMeta.jl, the same operation can be written more concisely:

```{julia}
world_agg3 = @chain world begin
    dropmissing([:pop, :area_km2])
    groupby(:continent)
    @combine(
        :total_pop = sum(:pop),
        :total_area = sum(:area_km2),
        :n_countries = length(:name_long)
    )
end
```

Let's extend this example by calculating population density and selecting the top 3 most populous continents:

```{julia}
top_continents = @chain world begin
    dropmissing([:pop, :area_km2])
    groupby(:continent)
    @combine(
        :total_pop = sum(:pop),
        :total_area = sum(:area_km2),
        :n_countries = length(:name_long)
    )
    @rtransform(:pop_density = :total_pop / :total_area)
    @orderby(-:total_pop)
    first(3)
end
```

### Vector attribute joining {#sec-vector-attribute-joining}

Combining data from different sources is a common task in data preparation.
Joins do this by combining tables based on a shared 'key' variable.
DataFrames.jl provides several join functions including `leftjoin`, `innerjoin`, `rightjoin`, and `outerjoin`.

A common type of attribute join on spatial data is to join `DataFrames` to `GeoDataFrames`.
In the following example, we combine data on coffee production with the `world` dataset.
The coffee data is in a CSV file containing major coffee-producing nations:

```{julia}
using CSV
coffee_data = CSV.read("data/coffee_data.csv", DataFrame)
first(coffee_data, 5)
```

Its columns are `name_long` (country name), and `coffee_production_2016` and `coffee_production_2017` (estimated values for coffee production in units of 60-kg bags per year).

A left join preserves all rows from the first dataset and adds matching columns from the second:

```{julia}
world_coffee = leftjoin(world, coffee_data, on = :name_long)
```

The result is a `DataFrame` with the same number of rows as `world` (177), but with two new columns for coffee production.
Countries without coffee production data have `missing` values in these columns.

We can check how many countries have coffee data:

```{julia}
coffee_countries = dropmissing(world_coffee, :coffee_production_2017)
println("Countries with 2017 coffee data: $(nrow(coffee_countries))")
```

What if we only want to keep countries that have a match in the key variable?
An inner join keeps only rows with matches in both datasets:

```{julia}
world_coffee_inner = innerjoin(world, coffee_data, on = :name_long)
println("Rows after inner join: $(nrow(world_coffee_inner))")
```

Note that the inner join has fewer rows than `coffee_data` (47 rows).
This is because some country names don't match exactly.
We can identify the mismatches:

```{julia}
coffee_names = Set(coffee_data.name_long)
world_names = Set(world.name_long)
setdiff(coffee_names, world_names)
```

The "Congo, Dem. Rep. of" name doesn't match the `world` dataset's naming convention.
We can fix this by updating the coffee data before joining:

```{julia}
# Find the correct name in world
drc_name = filter(n -> occursin("Dem", n) && occursin("Congo", n), world.name_long)
println("DRC name in world: $drc_name")

# Create a corrected copy
coffee_fixed = copy(coffee_data)
coffee_fixed.name_long = replace.(coffee_fixed.name_long, "Congo, Dem. Rep. of" => first(drc_name))

# Now the inner join captures one more country
world_coffee_fixed = innerjoin(world, coffee_fixed, on = :name_long)
println("Rows after fix: $(nrow(world_coffee_fixed))")
```

::: {.callout-note}
## Join column names

When the key columns have different names in each dataset, use the `on` argument with a `Pair`:

```julia
leftjoin(df1, df2, on = :name_in_df1 => :name_in_df2)
```
:::

### Creating attributes and removing spatial information {#sec-vec-attr-creation}

Often, we want to create new columns based on existing ones.
For example, calculating population density for each country requires dividing population by area.

In base Julia, we can add a new column directly:

```{julia}
world2 = copy(world)  # don't modify the original
world2.pop_density = world2.pop ./ world2.area_km2
select(world2, :name_long, :pop, :area_km2, :pop_density) |> first
```

Note the broadcasting operator `.` in `./` — this is essential for element-wise division in Julia.

Using DataFramesMeta.jl's `@rtransform` macro (row-wise transform):

```{julia}
world3 = @chain world begin
    @rtransform(:pop_density = :pop / :area_km2)
    @select(:name_long, :pop, :area_km2, :pop_density)
end
first(world3, 3)
```

To combine existing columns into a new one, we can use string interpolation or concatenation:

```{julia}
world4 = @chain world begin
    @rtransform(:con_reg = :continent * ":" * :region_un)
    @select(:name_long, :continent, :region_un, :con_reg)
end
first(world4, 3)
```

The opposite operation — splitting one column into multiple — uses the `split` function:

```{julia}
# Split the combined column back
world5 = @chain world4 begin
    @rtransform(
        :continent_new = split(:con_reg, ":")[1],
        :region_new = split(:con_reg, ":")[2]
    )
    @select(:name_long, :con_reg, :continent_new, :region_new)
end
first(world5, 3)
```

Renaming columns is done with the `rename` function:

```{julia}
world_renamed = rename(world, :name_long => :name, :pop => :population)
names(world_renamed)
```

To rename all columns at once, assign to the `names!` function:

```{julia}
world_short = copy(world)
rename!(world_short, names(world_short) .=> [:geom, :iso, :name, :cont, :reg, :subreg, :type, :area, :pop, :life, :gdp])
names(world_short)
```

Each of these attribute operations preserves the geometry column.
Sometimes, however, it makes sense to remove the geometry — for example, to speed up aggregation or to export just the attribute data.

To drop the geometry column, subset to exclude it:

```{julia}
geom_cols = GI.geometrycolumns(world)
world_df = select(world, Not(geom_cols...))
typeof(world_df)
```

The result is a regular `DataFrame` without spatial information.




## Manipulating raster objects

In contrast to the vector data model underlying simple features (which represents points, lines and polygons as discrete entities in space), raster data represent continuous surfaces.
This section shows how raster objects work by creating them *from scratch*, building on Section \@ref(an-introduction-to-terra).
Because of their unique structure, subsetting and other operations on raster datasets work in a different way, as demonstrated in Section \@ref(raster-subsetting).


The following code recreates the raster dataset used in Section \@ref(raster-classes), the result of which is illustrated in Figure \@ref(fig:cont-raster).
This demonstrates how the `Raster()` constructor works to create an example raster named `elev` (representing elevations).

```{julia}
vals = reshape(1:36, 6, 6)
elev = Raster(vals, (X(LinRange(-1.5, 1.5, 6)), Y(LinRange(-1.5, 1.5, 6))))
```


The result is a raster object with 6 rows and 6 columns, and spatial lookup vectors for the dimensions `X` (horizontal) and `Y` (vertical).
The `vals` argument sets the values that each cell contains: numeric data ranging from 1 to 36 in this case.


Raster objects can also contain categorical values, like strings or even values corresponding to categories.
The following code creates the raster datasets shown in Figure \@ref(fig:cont-raster):

```{julia}
# First, construct a categorical array
using CategoricalArrays

grain_order = ["clay", "silt", "sand"]
grain_char = rand(grain_order, 6, 6)
grain_fact = CategoricalArray(grain_char, levels = grain_order)

using Rasters
# Then, wrap the categorical array in a Raster object
grain = Raster(grain_fact, (X(LinRange(-1.5, 1.5, 6)), Y(LinRange(-1.5, 1.5, 6))))
```

This `CategoricalArray` is stored in two parts: a matrix of integer codes, and a dictionary of levels, that maps the integer codes to the string values.
We can retrieve the levels of a `CategoricalArray` using the `levels` function, and modify them using the `recode` function.

```{julia}
levels(grain)
```

```{julia}
grain2 = recode(grain, "clay" => "very wet", "silt" => "moist", "sand" => "dry")
```

```{julia}
#| echo: false
using Makie, CairoMakie, AlgebraOfGraphics
using Rasters
elev = Raster("output/elev.tif")
grain = Raster("output/grain.tif")

fig = Figure(size = (1000, 500))

a1, p1 = heatmap(fig[1, 1], elev; axis = (; title = "Elevation"))
cb = Colorbar(fig[1, 2], p1)

a2, p2 = heatmap(fig[1, 3], grain; colormap = Makie.Categorical([:brown, :sandybrown, :rosybrown]), axis = (; title = "Grain"), rasterize = false)
leg = Legend(fig[1, 4], [PolyElement(color = c) for c in collect(p2.colormap[].values)], ["clay", "silt", "sand"], rasterize = false)
fig
```

::: {.callout-note collapse="true"}

## Color tables in rasters

Rasters.jl does not currently support color tables in rasters.  This should come at some point, though.  ArchGDAL, the backend, does support these.

:::

### Raster subsetting

Raster subsetting is done with the Julia `getindex` syntax (square brackets), in the same way as we used it to subset DataFrames.
Raster selection is, however, far more powerful, since you can use [selectors](https://rafaqz.github.io/DimensionalData.jl/stable/) to select various spatial subsets of the raster, like `Near`, `At`, `Between`, and `..` (interval).

The `Near` selector finds the nearest cell to the specified coordinate — this is often the most practical choice:

```{julia}
elev[X(Near(0)), Y(Near(0))]
```

The `At` selector returns the value at an exact coordinate.
It requires the coordinate to match precisely, which can be tricky with floating-point values:

```{julia}
# Get exact coordinate values from the lookup
x_coords = lookup(elev, X)
y_coords = lookup(elev, Y)
println("X coordinates: ", collect(x_coords))
```

```{julia}
# Use the exact value from the lookup
elev[X(At(x_coords[2])), Y(At(y_coords[2]))]
```

The `..` operator (from IntervalSets.jl, re-exported by DimensionalData.jl) selects a range of values:

```{julia}
elev[X(-1..0), Y(0..1)]
```

This returns a smaller raster containing only the cells within the specified coordinate ranges.

You can also use integer indices directly, just like with arrays:

```{julia}
elev[1, 1]  # top-left cell
elev[1:3, 1:3]  # 3x3 subset from top-left
```

Cell values can be modified by combining subsetting with assignment.
The following sets the top-left cell to 0:

```{julia}
elev_modified = copy(elev)
elev_modified[1, 1] = 0
elev_modified[1:3, 1]  # check the first column
```

Multiple cells can be modified at once:

```{julia}
elev_modified[1, 1:3] .= 0  # set first row, columns 1-3 to 0
elev_modified[1:3, 1:3]
```

::: {.callout-note}
## Raster dimensions

Unlike numpy arrays (Python) where dimensions are typically `(rows, columns)` or `(y, x)`, Rasters.jl uses named dimensions.
When you write `elev[X(...), Y(...)]`, you're explicitly specifying which dimension you're selecting on, making the code more readable and less error-prone.

You can check a raster's dimensions with `dims(elev)`.
:::

### Summarizing raster objects {#sec-summarizing-raster-objects}

Julia's standard library and ecosystem provide many functions for summarizing raster values.
Since Rasters.jl rasters behave like arrays, standard functions work directly:

```{julia}
using Statistics

mean(elev)
```

```{julia}
std(elev)
```

```{julia}
minimum(elev), maximum(elev)
```

For a quick summary, we can combine these:

```{julia}
println("Elevation statistics:")
println("  Min: $(minimum(elev))")
println("  Max: $(maximum(elev))")
println("  Mean: $(round(mean(elev), digits=2))")
println("  Std: $(round(std(elev), digits=2))")
```

When rasters contain missing values (`missing` in Julia), use the `skipmissing` function:

```{julia}
# Create a raster with missing values by first converting to a Union type
vals_missing = convert(Array{Union{Missing, Int}, 2}, collect(reshape(1:36, 6, 6)))
elev_with_missing = Raster(vals_missing, (X(LinRange(-1.5, 1.5, 6)), Y(LinRange(-1.5, 1.5, 6))))
elev_with_missing[1, 1] = missing
mean(skipmissing(elev_with_missing))
```

For categorical rasters, we can calculate frequency tables.
First, let's reload the grain raster from file (as an integer-coded raster):

```{julia}
import ArchGDAL
grain_int = Raster("output/grain.tif")
```

To get the frequency of each category:

```{julia}
using StatsBase
counts = countmap(vec(grain_int))
```

Raster value statistics can be visualized in various ways.
A histogram shows the distribution of values in a continuous raster:

```{julia}
#| label: fig-raster-hist
#| fig-cap: Distribution of cell values in a continuous raster (`elev`)
using CairoMakie

fig = Figure(size=(600, 400))
ax = Axis(fig[1, 1], xlabel="Elevation", ylabel="Frequency", title="Elevation Distribution")
hist!(ax, vec(elev), bins=10)
fig
```

For categorical rasters, a bar plot is more appropriate:

```{julia}
#| label: fig-raster-bar
#| fig-cap: Distribution of cell values in a categorical raster (`grain`)
grain_labels = ["clay", "silt", "sand"]
grain_counts = [count(==(i), vec(grain_int)) for i in 1:3]

fig = Figure(size=(600, 400))
ax = Axis(fig[1, 1],
    xlabel="Grain type",
    ylabel="Count",
    title="Grain Type Distribution",
    xticks=(1:3, grain_labels)
)
barplot!(ax, 1:3, grain_counts)
fig
```

::: {.callout-note}
## Global vs local operations

The summary statistics shown here are *global* operations — they summarize the entire raster into a single value or set of values.
In contrast, *local* operations (covered in the next chapter) compute values for each cell based on its neighbors or corresponding cells in other layers.
:::

## Exercises

```{julia}
#| echo: false
#| output: false
# Exercises would go here
```

1. Create a new column in the `world` dataset called `pop_millions` that contains the population in millions (divide `pop` by 1,000,000). Which country has the highest population?

2. Using `groupby` and `combine`, calculate the mean life expectancy (`lifeExp`) by continent. Which continent has the highest average life expectancy?

3. Perform an inner join between `world` and `coffee_data`. How many rows are in the result? Why is this different from the number of rows in `coffee_data`?

4. Create a 10x10 raster with random values between 0 and 100. Calculate its mean, median, and standard deviation.

5. Subset the `elev` raster to only include cells where the elevation is greater than 20. How many cells remain?

