on:
  push:
    branches:
      [main]
name: Render
jobs:
  bookdown:
    name: GH-Pages
    runs-on: ubuntu-latest
    container: ghcr.io/geocompx/docker:julia
    defaults:
      run:
        shell: bash -l {0}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'
      - name: Render
        run: |
          julia -e 'using Pkg; Pkg.add("IJulia")'
          julia -e 'using IJulia'
          julia -e 'using Pkg; Pkg.add("Revise")'         
          # quarto check jupyter
          quarto render
          ls docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          commit_message: 'Deploy commit: ${{ github.event.head_commit.message }}'
