on:
  workflow_dispatch:
  push:
    branches:
      [main]
name: Quarto Publish
jobs:
  bookdown:
    name: GH-Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v2
      - uses: julia-actions/cache@v2
      - name: Set up custom Julia dependencies
        run: |
          using Pkg
          Pkg.activate("@quarto")
          Pkg.add(url = "https://github.com/asinghvi17/QuartoNotebookRunner.jl", rev = "as/execute-dir")
          Pkg.instantiate()
          Pkg.activate(".")
          Pkg.add([
            PackageSpec(url = "https://github.com/asinghvi17/Rasters.jl", rev = "as/fixrasterize"),
          ])
        shell: julia
      - uses: julia-actions/julia-buildpkg@v1

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          QUARTO_JULIA_PROJECT: "@quarto"

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUARTO_JULIA_PROJECT: "@quarto"
