on:
  workflow_dispatch:
  pull_request:
    branches:
      [main]
name: Quarto PR Publish
jobs:
  bookdown:
    name: GH-Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
      pull-requests: write
      deployments: write
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v2
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render 
        uses: quarto-dev/quarto-actions/render@v2
        with: 
          to: html

      - name: Deploy Preview to Netlify as preview
        id: netlify-deploy
        uses: nwtgck/actions-netlify@v3
        env:
          NETLIFY_SITE_ID: e18690e5-215e-4584-b0f1-963bc99a10d0
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        with:
          publish-dir: './docs'
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: |
            Deploy from GHA: ${{ github.event.pull_request.title || format('manual from PR {0}', github.event.issue.number) }}
          alias: deploy-preview-${{ github.event.pull_request.number || github.event.issue.number }}
          # these all default to 'true'
          enable-pull-request-comment: true
          enable-commit-comment: false
          enable-commit-status: true
          overwrites-pull-request-comment: false
        timeout-minutes: 1
